# Generated by Django 2.1.2 on 2018-10-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAuth', '0004_auto_20181004_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mail_send',
        ),
        migrations.RemoveField(
            model_name='user',
            name='restore_password_uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_uuid',
        ),
    ]
